name: Walker_repo
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - pandas
  - matplotlib
  - scipy
  - jupyter
  - nbformat
  -PyQt5:
    -QtCore
    -QtGui
    -QtWidgets
  - pip
  - pip:
    - nmrglue
